Security-Onion-Solutions/security-onion#1392 Security-Onion-Solutions/security-onion#1393

diff --git a/files/debian/ossec-hids-server.postinst b/files/debian/ossec-hids-server.postinst
--- a/files/debian/ossec-hids-server.postinst
+++ b/files/debian/ossec-hids-server.postinst
@@ -145,12 +145,28 @@ chmod -R 770 ${DIR}/queue/vulnerabilities 2> /dev/null || /bin/true
 # ruleset root:ossec 750 don't recurse
 chown -R root:${GROUP} ${DIR}/ruleset 2> /dev/null || /bin/true
 chmod 750 ${DIR}/ruleset 2> /dev/null || /bin/true
-ln -s ../rules /var/ossec/ruleset/rules 2> /dev/null || /bin/true
-ln -s ../etc/decoders /var/ossec/ruleset/decoders 2> /dev/null || /bin/true
+if [ -e /var/ossec/ruleset/rules ]; then
+	echo "/var/ossec/ruleset/rules already exists."
+else
+	ln -s ../rules /var/ossec/ruleset/rules 2> /dev/null || echo "Error creating symlink."
+fi
+if [ -e /var/ossec/ruleset/decoders ]; then
+	echo "/var/ossec/ruleset/decoders already exists."
+else
+	ln -s ../etc/decoders /var/ossec/ruleset/decoders 2> /dev/null || echo "Error creating symlink."
+fi
+
+# var/db root:ossec 770
+chown -R root:${GROUP} ${DIR}/var/db 2> /dev/null || /bin/true
+chmod -R 770 ${DIR}/var/db 2> /dev/null || /bin/true
 
 # var/download root:ossec 770
 chown -R root:${GROUP} ${DIR}/var/download 2> /dev/null || /bin/true
 chmod -R 770 ${DIR}/var/download 2> /dev/null || /bin/true
+
+# var/multigroups root:ossec 770
+chown -R root:${GROUP} ${DIR}/var/multigroups 2> /dev/null || /bin/true
+chmod -R 770 ${DIR}/var/multigroups 2> /dev/null || /bin/true
 
 # var/selinux root:ossec 770
 chown -R root:${GROUP} ${DIR}/var/selinux 2> /dev/null || /bin/true
@@ -219,7 +235,7 @@ chown root:${GROUP} ${DIR}/var/run
 # [...]
 touch ${DIR}/etc/shared/ar.conf
 chown -R root:${GROUP} ${DIR}/etc/decoders 2>/dev/null || /bin/true
-chown root:${GROUP} ${DIR}/etc/local_decoder.xml 2>/dev/null || /bin/true
+chown root:${GROUP} ${DIR}/etc/local_decoders/local_decoder.xml 2>/dev/null || /bin/true
 chown root:${GROUP} ${DIR}/etc/internal_options.conf
 chown root:${GROUP} ${DIR}/etc/local_internal_options.conf 2>/dev/null || /bin/true
 chown root:${GROUP} ${DIR}/etc/client.keys 2>/dev/null || /bin/true
@@ -227,7 +243,7 @@ chown root:${GROUP} ${DIR}/etc/shared/*
 chown root:${GROUP} ${DIR}/agentless/*
 chown ${USER}:${GROUP} ${DIR}/.ssh
 chmod -R 440 ${DIR}/etc/decoders 2>/dev/null || /bin/true
-chmod 440 ${DIR}/etc/local_decoder.xml 2>/dev/null || /bin/true
+chmod 440 ${DIR}/etc/local_decoders/local_decoder.xml 2>/dev/null || /bin/true
 chmod 440 ${DIR}/etc/internal_options.conf
 chmod 440 ${DIR}/etc/local_internal_options.conf 2>/dev/null || /bin/true
 chmod 440 ${DIR}/etc/client.keys 2>/dev/null || /bin/true
@@ -261,7 +277,11 @@ chmod 440 ${DIR}/etc/ossec.conf
 
 # /var/ossec/etc/ossec-init.conf should be a symlink to /etc/ossec-init.conf
 # https://github.com/Security-Onion-Solutions/security-onion/issues/1360
-ln -s /etc/ossec-init.conf ${DIR}/etc/ossec-init.conf
+if [ -e ${DIR}/etc/ossec-init.conf ]; then
+	echo "${DIR}/etc/ossec-init.conf already exists."
+else
+	ln -s /etc/ossec-init.conf ${DIR}/etc/ossec-init.conf || echo "Error creating ${DIR}/etc/ossec-init.conf"
+fi
 
 #################
 # Security Onion 
